management:
  endpoints:
    jmx:
      exposure:
        include: "*"
        exclude:
    web:
      base-path: /management
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
springdoc:
  swagger-ui:
    enabled: true
application:
  description: ${APP_DESCRIPTION}
  version: ${APP_VERSION}
server:
  #address: ${APP_SERVER_ADDRESS:localhost}
  port: ${APP_SERVER_PORT:3030}
  #context-path: /userregistration
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: ${SPRING_APPLICATION_NAME:userregistrationflyway}
  datasource:
    driver-class-name: org.postgresql.Driver
    initialize: true
    password: ${APP_DB_PASSWORD:admin}
    platform: postgres
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dbuserregistrationflyway:5432/postgres}
    username: ${APP_DB_USERNAME:postgres}
    #initialization-mode: always
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        generate_statistics: true
    show-sql: true
---
server:
  # address: xx.xx.xx.xx
  # port: yyyy
  context-path: /userregistration
spring:
  profiles: prod
  application:
    name: userregistration
  datasource:
    driver-class-name: org.postgresql.Driver
    initialize: true
    password: uvsoftgroup01
    platform: postgres
    url: jdbc:postgresql://xxx.xx.xx.xx:5432/uvsoftgroup01
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
---
server:
  # address: xx.xx.xx.xx
  # port: yyyy
  context-path: /userregistration
spring:
  profiles: test
  application:
    name: userregistration
  datasource:
    driver-class-name: org.postgresql.Driver
    initialize: true
    password: uvsoftgroup02
    platform: postgres
    url: jdbc:postgresql://xxx.xx.xx.xx:5432/uvsoftgroup02
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
