DROP SEQUENCE IF EXISTS seq_userrole;
CREATE SEQUENCE seq_userrole INCREMENT 1 START 100;
DROP SEQUENCE IF EXISTS seq_useregistration;
CREATE SEQUENCE seq_useregistration INCREMENT 1 START 200;
DROP SEQUENCE IF EXISTS seq_urprofile;
CREATE SEQUENCE seq_urprofile INCREMENT 1 START 300;
